### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback, class 'bdImage_XenForo_Image_ImageMagick_Pecl' not found

### ISSUE THREAD

**Issue by draft1** [xfrocks/bdImage#1]
Server Error Log

Error Info
ErrorException: call_user_func() expects parameter 1 to be a valid callback, class 'bdImage_XenForo_Image_ImageMagick_Pecl' not found - library/XenForo/Image/Abstract.php:254
Generated By: User, A moment ago
Stack Trace
#0 /library/XenForo/Image/Abstract.php(254): XenForo_Application::handlePhpError(2, 'call_user_func(...', '/home/nginx/dom...', 254, Array)
#1 /library/XenForo/Model/Attachment.php(502): XenForo_Image_Abstract::createFromFile('/tmp/phpGR2uFc', 2)
#2 /library/XenForo/ControllerPublic/Attachment.php(205): XenForo_Model_Attachment->insertUploadedAttachmentData(Object(XenForo_Upload), 1)
#3 /library/XenForo/FrontController.php(351): XenForo_ControllerPublic_Attachment->actionDoUpload()
#4 /library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /index.php(13): XenForo_FrontController->run()
#6 {main}

Request State
array(3) {
  ["url"] => string(104) "https://domain.com/attachments/do-upload.json?hash=b7b7b4108d87298d0ea78f742743047f&content_type=post"
  ["_GET"] => array(3) {
    ["/attachments/do-upload_json"] => string(0) ""
    ["hash"] => string(32) "b7b7b4108d87298d0ea78f742743047f"
    ["content_type"] => string(4) "post"
  }
  ["_POST"] => array(13) {
    ["_xfToken"] => string(8) "********"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
    ["_xfSessionId"] => string(32) "266446b1dfbca32b1e2df596c6734f62"
    ["content_data"] => array(1) {
      ["node_id"] => string(1) "2"
    }
    ["flowChunkNumber"] => string(1) "1"
    ["flowChunkSize"] => string(10) "4294967296"
    ["flowCurrentChunkSize"] => string(5) "37474"
    ["flowTotalSize"] => string(5) "37474"
    ["flowIdentifier"] => string(11) "37474-wejpg"
    ["flowFilename"] => string(6) "we.jpg"
    ["flowRelativePath"] => string(6) "we.jpg"
    ["flowTotalChunks"] => string(1) "1"
  }
}

**Comment by daohoangson** [comment]
We have a few sites running [bd] Image with ImageMagick and this error never occurred. How did it happen? Is this a new site or you changed something? Btw, please confirm your php version and add-on version please?

**Comment by draft1** [comment]
This is new Site.

PHP Version 7.1.6
imagick module version - 3.4.3
Imagick compiled with ImageMagick version - ImageMagick 6.9.8-9 Q16 x86_64 2017-06-06 
Imagick using ImageMagick library version - ImageMagick 6.9.8-9 Q16 x86_64 2017-06-06 

I'm using this version itself: https://github.com/xfrocks/bdImage/archive/master.zip

Happens when I upload a new Image when creating thread.

**Comment by daohoangson** [comment]
Have you been able to tracked down this issue? @RoldanLT

**Comment by draft1** [comment]
No I haven't.

**Comment by draft1** [comment]
I have updated to the latest version of this addon and error still exist.

**Comment by daohoangson** [comment]
I have just fixed a typo in the repo. Can you please try again?

**Comment by draft1** [comment]
Yay thanks a lot!
Works great now.
