### ISSUE TITLE
Doesn't work with Convert Image adoon

### ISSUE THREAD

**Issue by draft1** [xfrocks/bdImage#2]
https://xenforo.com/community/resources/convert-image.2521/

Auto thumbnail generation doesn't work when both addon is enabled.

**Comment by daohoangson** [comment]
So it does convert but no attachment thumbnail?

**Comment by draft1** [comment]
Yes it does converted fine but BDImage doesn't work for thumbnail generation.
I think it's because of this error: https://github.com/xfrocks/bdImage/issues/1

**Comment by daohoangson** [comment]
Yes, if this is the same server then #1 would be the cause for this.

**Comment by daohoangson** [comment]
@RoldanLT, with #1 being resolved. Does it work with the other add-on now?

**Comment by draft1** [comment]
No error log show up but still:

> Auto thumbnail generation doesn't work when both addon is enabled.

> Yes it does converted fine but BDImage doesn't work for thumbnail generation.

**Comment by daohoangson** [comment]
Hmm, for links that have been converted successfully, clicking to view the full size attachment works but no attachment thumbnail? And no error at all?! Do you have this on a live site?

**Comment by draft1** [comment]
> for links that have been converted successfully, clicking to view the full size attachment works

Yes.

> but no attachment thumbnail?

Yes should I generate? 
I even don't know how to generate thumbnail as it is inserted automatically as full.

> And no error at all?

No.

> Do you have this on a live site?

This is on my dev site local, just planning to apply on my live forum.

**Comment by draft1** [comment]
I inserted the images as thumbnail and it works now :D.

**Comment by daohoangson** [comment]
Hmm, so it works? I will be closing this issue now, is that okie? @RoldanLT

**Comment by draft1** [comment]
When thumbnail is inserted, Yes.
