### ISSUE TITLE
Declaration of bdImage_WidgetRenderer_ThreadsTwo::_getLayoutOptions

### ISSUE THREAD

**Issue by ngtrian** [xfrocks/bdImage#4]
```
Declaration of bdImage_WidgetRenderer_ThreadsTwo::_getLayoutOptions(array $widget, $positionCode, array $params, XenForo_Template_Abstract $renderTemplateObject) should be compatible with WidgetFramework_WidgetRenderer_Threads::_getLayoutOptions($widget, $positionCode, $params, $layout) - library/bdImage/WidgetRenderer/ThreadsTwo.php:0
```

Error display when I  view a wiget or add a widget in Widget Framework 2.6.3
My system info
php-fpm 7.0
mysql 5.7

**Comment by daohoangson** [comment]
Which version of Widget Framework are you using exactly? v2.6.3 has several different sub-releases.

**Comment by ngtrian** [comment]
It's [bd] Widget Framework 2.6.3-BETA18

**Comment by daohoangson** [comment]
Looks like it requires Widget Framework beta 20 to work. I have made the changes to not init those widget renderer unless the correct version is installed (see 91a20e9).

If you do plan to use the widgets, just upgrade Widget Framework when you need them.

**Comment by ngtrian** [comment]
I just update Widget Framework, It's working
Thanks!
