### ISSUE TITLE
the picker.js file is located wrong.

### ISSUE THREAD

**Issue by ghost** [xfrocks/bdImage#8]
/js/bdImage/full/picker.js gives 404

i changed it to: /js/bdImage/picker.min.js

that fixed it.

**Comment by daohoangson** [comment]
Which version are you reporting for?

Also, which file did you make the change to?

**Comment by ghost** [comment]
i used the master download here on github. 

this one: /js/bdImage/full/picker.js

**Comment by ghost** [comment]
aaah you din't include it yet because you are still modifying the javascript file. sorry for the confusion.
